name: CI
on: push
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16.x' ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install Dependencies
        run: npm install

      - name: Run Eslint checks
        run: npm run lint
